classes:
  - id: 0
    name: "wall"
    color: [179, 136, 92]
  - id: 1
    name: "equipment"
    color: [255, 80, 80]
  - id: 2
    name: "human"
    color: [80, 220, 120]
  - id: 3
    name: "conveyor"
    color: [245, 180, 65]
  - id: 4
    name: "roof"
    color: [120, 170, 255]
  - id: 5
    name: "other"
    color: [120, 120, 255]
